suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(patchwork)
})
source('R/plotting/plotting_functions.R')
source('R/server/server_functions.R')
stopifnot(all(atop_pathway_colors(20) %in% atop_palette))
counts <- data.frame(Gene = rep('A', 4), gRNA = letters[1:4], treatment = c(2,4,6,8), control = c(5,6,9,11))
paired <- generate_sgrna_paired_plot(counts, 'A', 'gRNA', 'Gene', 'treatment', 'control')
stopifnot(paired$theme$text$size == 8, paired$theme$axis.text$size == 8)
stopifnot(identical(unname(paired$scales$get_scales('colour')$palette(2)), c('#104e8b','#b22222')))
out <- file.path(Sys.getenv('TMPDIR', '/tmp'), 'atop-figure-style')
dir.create(out, showWarnings = FALSE)
ggsave(file.path(out, 'paired.svg'), paired, width = 8.5, height = 10.5, units = 'cm')
ggsave(file.path(out, 'paired.png'), paired, width = 8.5, height = 10.5, units = 'cm', dpi = 160)
svg <- paste(readLines(file.path(out,'paired.svg')), collapse = '\n')
stopifnot(grepl("width='240.94pt'", svg, fixed = TRUE), grepl("height='297.64pt'", svg, fixed = TRUE))
sets <- data.frame(ID = c('P1','P2','P3'), Description = c('Pathway one','Pathway two','Pathway three'), NES = c(1.2,1.8,2.3), pvalue = c(.02,.01,.005), setSize = c(20,30,40))
sets$p.adjust <- sets$pvalue
lollipop <- generate_gsea_lollipop_plot_shiny(sets, 'Positive', 3, 'Pathways')
stopifnot(lollipop$theme$text$size == 8)
ggsave(file.path(out,'lollipop.png'), lollipop, width = 18, height = 14, units = 'cm', dpi = 160)
suppressPackageStartupMessages(library(clusterProfiler))
ranks <- setNames(seq(3,-3,length.out=200),paste0('G',1:200))
pathways <- data.frame(term=rep(c('SET_A','SET_B'),each=30), gene=c(names(ranks)[1:30],names(ranks)[171:200]))
set.seed(1)
gsea <- suppressWarnings(clusterProfiler::GSEA(ranks, TERM2GENE=pathways, minGSSize=10, pvalueCutoff=1, nPerm=100, verbose=FALSE))
for (n in 1:2) {
  p <- generate_gsea_multi_pathway_plot(gsea, c('SET_A','SET_B')[seq_len(n)], add_pval=TRUE)
  ggsave(file.path(out,paste0('enrichment-',n,'.png')),p,width=16,height=12,units='cm',dpi=160)
}
cat('PASS: 8 pt typography, palette, cm SVG dimensions, paired/lollipop/enrichment exports.\n')
cat('QA directory:', out, '\n')

stopifnot(paired$theme$text$family == 'Arial', lollipop$theme$axis.text$colour == 'black')
ggsave(file.path(out, 'paired.pdf'), paired, width = 8.5, height = 10.5, units = 'cm', device = publication_device('pdf'))
stopifnot(grepl('Arial', svg, fixed = TRUE))
